name: build-test-azure-extension
on: [push]

# test workflow

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      # - name: setup pnpm
      #   uses: .github/actions/install-pnpm-build
      # with:
      #   node_version: "14"
      - name: checkout
        uses: actions/checkout@v3

      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.21.0

      - name: setup node11
        uses: actions/setup-node@v3
        with:
          node-version: "19.9.0"

      - name: install packages
        run: pnpm install --no-frozen-lockfile

      - name: build package
        run: pnpm run build

      - name: Install tfx-cli
        run: pnpm install --global tfx-cli

      - name: current path
        run: |
          current_directory=$(pwd)
          echo "Current directory: $current_directory"

      - name: pack task V2
        run: pnpm run pack:Azure:v2

      - name: build azure task
        run: |
          azure_task_dir="/home/runner/work/my_pullRequest/my_pullRequest/apps/azure-task";
          tfx extension create --root . "$azure_task_dir/.dist" --manifest-globs "$azure_task_dir/.dist/vss-extension.json" --output-path "$azure_task_dir/.dist"
        shell: bash

      # - name: upload coverage reports to codcov
      #   if: ${{ !github.event.act }}
      #   uses: codecov/codecov-action@v3
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    # pack azure-devops-task
    # create artifact

  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: deploy-to-marketplace
  #       run: |
  #         tfx extension publish \
  #           --publisher "avinash-live-pr" \
  #           --vsix "$azure_task_dir/.dist/avinash-live-pr.build-release-task-0.0.91.vsix" \
  #           --token "tnlywzsj2r53dge4n3qhpzjes52rynblhxphi4i5hqppseqbmtua" \
  #           --output-path "$azure_task_dir/.dist"
