name: build-test-azure-extension
on: [push]

# test workflow

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      # - name: setup pnpm
      #   uses: .github/actions/install-pnpm-build
      # with:
      #   node_version: "14"
      - name: checkout
        uses: actions/checkout@v3

      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: setup node11
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: install packages
        run: pnpm install --no-frozen-lockfile

      - name: build package
        run: pnpm run build

      - name: test
        run: |
          ls -al ./apps/azure-task

      - name: pack task V1
        run: |
          chmod 755 ./scripts/pack-azure-task.sh
          ./scripts/pack-azure-task.sh v1
        shell: bash

      # - name: pack task V2
      #   run: pnpm run pack:Azure:v2

      - name: upload coverage reports to codcov
        if: ${{ !github.event.act }}
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    # pack azure-devops-task
    # create artifact
